# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Nibir Hossain
# Description of the Site
description: A passionate Developer and Entrepreneur
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Software, Developer, Entrepreneur, Project Lead, Backend Developer
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/heroimage.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: Nibir.Hossain85@gmail.com
facebook_username: nibir.hossain.54
twitter_username: /
instagram_username: /
linkedin_username: nibir-hossain
github_username:  nibirhossain
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Nibir Hossain
# URL for the Image of the Author
# author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-image: /assets/images/profile.jpg
# 60 Words About the Author
author-about: |
  Hi, I am Nibir, a passionate and professional Software Engineer (Project Lead) who loves developing systems in the area of Microservices and Machine Learning. In my past few years, I designed and developed some distributed systems and a robot process automation system using Spring Boot, RabbitMQ, and Apache Kafka.
  <br><br>Recently I completed some important Machine Learning, Deep Learning, and TensorFlow courses and acquired solid knowledge in the field of Artificial Intelligence.
  <br><br>I would like to combine my software development experience and Machine Learning skills together for developing sophisticated software and bringing important value to your organization.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/nibirhossain

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
